import { UserRole } from '@openclinic/core/enums';
import type { BlockRecurrence } from '../../domain/schedule-block.js';
import { sql } from 'drizzle-orm';
import { pgTable, varchar, text, boolean, integer, timestamp, jsonb, date, uniqueIndex, index, foreignKey, unique, check } from 'drizzle-orm/pg-core';

// -- SYS_* Tables --
export const sysTenants = pgTable('sys_tenants', {
  id: varchar('id', { length: 36 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 100 }).unique('sys_tenants_slug_key'),
  status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
  tax_id: varchar('tax_id', { length: 50 }),
  cnpj: varchar('cnpj', { length: 14 }),
  contact_name: varchar('contact_name', { length: 255 }),
  contact_title: varchar('contact_title', { length: 100 }),
  contact_email: varchar('contact_email', { length: 255 }),
  contact_phone: varchar('contact_phone', { length: 20 }),
  postal_code: varchar('postal_code', { length: 20 }),
  street: varchar('street', { length: 255 }),
  number: varchar('number', { length: 20 }),
  complement: varchar('complement', { length: 100 }),
  neighborhood: varchar('neighborhood', { length: 100 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 100 }),
  country: varchar('country', { length: 50 }),
  is_default: boolean('is_default').notNull().default(false),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_sys_tenants_cnpj').on(table.cnpj),
  index('idx_sys_tenants_status').on(table.status),
]);

export const sysApplications = pgTable('sys_applications', {
  id: varchar('id', { length: 36 }).primaryKey(),
  code: varchar('code', { length: 100 }).unique('sys_applications_code_key').notNull(),
  appName: varchar('app_name', { length: 255 }).notNull(),
  appVersion: varchar('app_version', { length: 50 }).notNull(),
  appLogoUrl: varchar('app_logo_url', { length: 500 }),
  appFaviconUrl: varchar('app_favicon_url', { length: 500 }),
  appSubtitle: varchar('app_subtitle', { length: 255 }),
  appDescription: text('app_description'),
  defaultLocale: varchar('default_locale', { length: 10 }).notNull(),
  defaultSupportedLocales: jsonb('default_supported_locales').notNull(),
  defaultTimezone: varchar('default_timezone', { length: 50 }).notNull(),
  defaultDialingCode: varchar('default_dialing_code', { length: 5 }).notNull(),
  defaultMaxLoginAttempts: integer('default_max_login_attempts').notNull(),
  defaultLockoutDurationMinutes: integer('default_lockout_duration_minutes').notNull(),
  defaultSessionTimeoutMinutes: integer('default_session_timeout_minutes').notNull(),
  defaultMinPasswordLength: integer('default_min_password_length').notNull(),
  defaultMfaEnabled: boolean('default_mfa_enabled').notNull().default(false),
  defaultPasswordResetTokenTtlHours: integer('default_password_reset_token_ttl_hours').notNull(),
  defaultEnableAuditLog: boolean('default_enable_audit_log').notNull().default(true),
  defaultAuditRetentionDays: integer('default_audit_retention_days').notNull(),
  defaultAcceptedLoginMethods: jsonb('default_accepted_login_methods').notNull(),
  defaultExtraSettings: jsonb('default_extra_settings').notNull().default({}),
  primaryLoginIdentifier: varchar('primary_login_identifier', { length: 20 }).notNull(),
  allowDirectUserCreation: boolean('allow_direct_user_creation').notNull().default(false),
  isMultiTenant: boolean('is_multi_tenant').notNull().default(false),
  isDefaultApplication: boolean('is_default_application').notNull().default(false),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_sys_applications_is_active').on(table.isActive),
]);

export const sysApplicationConfigs = pgTable('sys_application_configs', {
  id: varchar('id', { length: 36 }).primaryKey(),
  application_id: varchar('application_id', { length: 36 }).notNull(),
  tenant_id: varchar('tenant_id', { length: 36 }),
  is_primary_for_tenant: boolean('is_primary_for_tenant').notNull().default(false),
  is_active: boolean('is_active').notNull().default(true),
  enforce_document_acceptance_on_login: boolean('enforce_document_acceptance_on_login').notNull().default(false),
  config_json: jsonb('config_json').notNull().default({}),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  foreignKey({ name: 'fk_sys_app_configs_application', columns: [table.application_id], foreignColumns: [sysApplications.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_sys_app_configs_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

export const sysAuditLogs = pgTable('sys_audit_logs', {
  id: varchar('id', { length: 36 }).primaryKey(),
  user_id: varchar('user_id', { length: 36 }),
  username: varchar('username', { length: 255 }),
  action: varchar('action', { length: 100 }).notNull(),
  resource: varchar('resource', { length: 255 }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('SUCCESS'),
  ip_address: varchar('ip_address', { length: 45 }),
  user_agent: text('user_agent'),
  details: jsonb('details'),
  tenant_id: varchar('tenant_id', { length: 36 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_sys_audit_logs_user_id').on(table.user_id),
  index('idx_sys_audit_logs_created_at').on(table.created_at),
  foreignKey({ name: 'fk_sys_audit_logs_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

// -- IAM_* Tables --
export const iamUsers = pgTable('iam_users', {
  id: varchar('id', { length: 36 }).primaryKey(),
  username: varchar('username', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  cpf: varchar('cpf', { length: 11 }),
  hashed_password: varchar('hashed_password', { length: 500 }),
  full_name: varchar('full_name', { length: 255 }).notNull(),
  display_name: varchar('display_name', { length: 255 }).notNull(),
  job_title: varchar('job_title', { length: 100 }),
  role: varchar('role', { length: 20 }).notNull().default(UserRole.USER),
  is_active: boolean('is_active').notNull().default(true),
  access_count: integer('access_count').notNull().default(0),
  last_access: timestamp('last_access', { withTimezone: true }),
  require_password_change: boolean('require_password_change').notNull().default(false),
  password_reset_token: varchar('password_reset_token', { length: 255 }),
  password_reset_expires_at: timestamp('password_reset_expires_at', { withTimezone: true }),
  tenant_id: varchar('tenant_id', { length: 36 }),
  is_tenant_owner: boolean('is_tenant_owner').notNull().default(false),
  timezone: varchar('timezone', { length: 50 }),
  locale: varchar('locale', { length: 10 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  // Identity is global, not per-tenant: login resolves an account from the identifier alone, so a
  // second row answering to the same email, username or CPF would make authentication ambiguous.
  // Case-insensitive because every read path lowercases its input; partial on deleted_at so a
  // soft-deleted account releases its identifier instead of blocking it forever.
  uniqueIndex('idx_iam_users_email_global').on(sql`lower(${table.email})`).where(sql`${table.deleted_at} is null`),
  uniqueIndex('idx_iam_users_username_global').on(sql`lower(${table.username})`).where(sql`${table.deleted_at} is null`),
  uniqueIndex('idx_iam_users_cpf_global').on(table.cpf).where(sql`${table.deleted_at} is null and ${table.cpf} is not null`),
  /** Backs exact-match username lookups, which the functional index above cannot answer. */
  index('idx_iam_users_username_lookup').on(table.username),
  index('idx_iam_users_role').on(table.role),
  index('idx_iam_users_tenant_id').on(table.tenant_id),
  index('idx_iam_users_deleted_at').on(table.deleted_at),
  foreignKey({ name: 'fk_iam_users_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

export const iamSessions = pgTable('iam_sessions', {
  id: varchar('id', { length: 36 }).primaryKey(),
  user_id: varchar('user_id', { length: 36 }).notNull(),
  token_hash: varchar('token_hash', { length: 500 }).notNull(),
  user_agent: text('user_agent'),
  ip_address: varchar('ip_address', { length: 45 }),
  expires_at: timestamp('expires_at', { withTimezone: true }).notNull(),
  revoked_at: timestamp('revoked_at', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_iam_sessions_token_hash').on(table.token_hash),
  index('idx_iam_sessions_user_id').on(table.user_id),
  index('idx_iam_sessions_expires_at').on(table.expires_at).where(sql`${table.revoked_at} IS NULL`),
  foreignKey({ name: 'fk_iam_sessions_user', columns: [table.user_id], foreignColumns: [iamUsers.id] }).onDelete('cascade'),
]);

export const iamLockouts = pgTable('iam_lockouts', {
  id: varchar('id', { length: 36 }).primaryKey(),
  identifier: varchar('identifier', { length: 255 }).notNull(),
  attempt_count: integer('attempt_count').notNull().default(0),
  locked_until: timestamp('locked_until', { withTimezone: true }),
  tenant_id: varchar('tenant_id', { length: 36 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_iam_lockouts_identifier').on(table.identifier),
  foreignKey({ name: 'fk_iam_lockouts_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

export const iamGroups = pgTable('iam_groups', {
  id: varchar('id', { length: 36 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  is_active: boolean('is_active').notNull().default(true),
  is_default: boolean('is_default').notNull().default(false),
  tenant_id: varchar('tenant_id', { length: 36 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  foreignKey({ name: 'fk_iam_groups_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

export const iamUserGroups = pgTable('iam_user_groups', {
  id: varchar('id', { length: 36 }).primaryKey(),
  user_id: varchar('user_id', { length: 36 }).notNull(),
  group_id: varchar('group_id', { length: 36 }).notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique('iam_user_groups_user_id_group_id_key').on(table.user_id, table.group_id),
  foreignKey({ name: 'fk_iam_user_groups_user', columns: [table.user_id], foreignColumns: [iamUsers.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_iam_user_groups_group', columns: [table.group_id], foreignColumns: [iamGroups.id] }).onDelete('cascade'),
]);

export const sysApplicationResources = pgTable('sys_application_resources', {
  id: varchar('id', { length: 36 }).primaryKey(),
  item_code: varchar('item_code', { length: 255 }).notNull(),
  resource_type: varchar('resource_type', { length: 20 }).notNull().default('API'),
  context: varchar('context', { length: 20 }).notNull().default('BUSINESS'),
  description: text('description'),
  parent_id: varchar('parent_id', { length: 36 }),
  path: varchar('path', { length: 500 }),
  label_key: varchar('label_key', { length: 255 }),
  icon: varchar('icon', { length: 100 }),
  route: varchar('route', { length: 500 }),
  sort_order: integer('sort_order').notNull().default(0),
  min_role: varchar('min_role', { length: 20 }).notNull().default(UserRole.USER),
  is_active: boolean('is_active').notNull().default(true),
  application_id: varchar('application_id', { length: 36 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  unique('uq_sys_resources_item_code').on(table.item_code),
  index('idx_sys_resources_item_code').on(table.item_code),
  index('idx_sys_resources_context').on(table.context),
  foreignKey({ name: 'fk_sys_app_resources_parent', columns: [table.parent_id], foreignColumns: [table.id] }).onDelete('set null'),
  foreignKey({ name: 'fk_sys_app_resources_application', columns: [table.application_id], foreignColumns: [sysApplications.id] }).onDelete('set null'),
]);

export const iamPermissions = pgTable('iam_permissions', {
  id: varchar('id', { length: 36 }).primaryKey(),
  user_id: varchar('user_id', { length: 36 }),
  group_id: varchar('group_id', { length: 36 }),
  resource_id: varchar('resource_id', { length: 36 }).notNull(),
  action: varchar('action', { length: 20 }).notNull().default('READ'),
  effect: varchar('effect', { length: 20 }).notNull().default('ALLOW'),
  is_active: boolean('is_active').notNull().default(true),
  tenant_id: varchar('tenant_id', { length: 36 }),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_iam_permissions_user_id').on(table.user_id),
  index('idx_iam_permissions_group_id').on(table.group_id),
  index('idx_iam_permissions_resource_id').on(table.resource_id),
  check('iam_permissions_check', sql`${table.user_id} IS NOT NULL OR ${table.group_id} IS NOT NULL`),
  foreignKey({ name: 'fk_iam_permissions_user', columns: [table.user_id], foreignColumns: [iamUsers.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_iam_permissions_group', columns: [table.group_id], foreignColumns: [iamGroups.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_iam_permissions_resource', columns: [table.resource_id], foreignColumns: [sysApplicationResources.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_iam_permissions_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('set null'),
]);

// -- APP_* Tables (Business & Clinical Domain - HL7 FHIR Aligned) --
export const appOrganizations = pgTable('app_organizations', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  legal_name: varchar('legal_name', { length: 255 }).notNull(),
  trade_name: varchar('trade_name', { length: 255 }).notNull(),
  tax_id: varchar('tax_id', { length: 50 }),
  cnpj: varchar('cnpj', { length: 14 }),
  state_registration: varchar('state_registration', { length: 30 }),
  municipal_registration: varchar('municipal_registration', { length: 30 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 20 }),
  website: varchar('website', { length: 255 }),
  postal_code: varchar('postal_code', { length: 20 }),
  street: varchar('street', { length: 255 }),
  number: varchar('number', { length: 20 }),
  complement: varchar('complement', { length: 100 }),
  neighborhood: varchar('neighborhood', { length: 100 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 100 }),
  country: varchar('country', { length: 50 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_organizations_tenant_id').on(table.tenant_id),
  index('idx_app_organizations_tax_id').on(table.tax_id),
  index('idx_app_organizations_cnpj').on(table.cnpj),
  index('idx_app_organizations_trade_name').on(table.tenant_id, table.trade_name),
  foreignKey({ name: 'fk_app_organizations_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
]);

export const appOrganizationUnits = pgTable('app_organization_units', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  organization_id: varchar('organization_id', { length: 36 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  trade_name: varchar('trade_name', { length: 255 }),
  cnes_code: varchar('cnes_code', { length: 15 }),
  tax_id: varchar('tax_id', { length: 50 }),
  cnpj: varchar('cnpj', { length: 14 }),
  phone: varchar('phone', { length: 20 }),
  email: varchar('email', { length: 255 }),
  postal_code: varchar('postal_code', { length: 20 }),
  street: varchar('street', { length: 255 }),
  number: varchar('number', { length: 20 }),
  complement: varchar('complement', { length: 100 }),
  neighborhood: varchar('neighborhood', { length: 100 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 100 }),
  country: varchar('country', { length: 50 }),
  is_headquarters: boolean('is_headquarters').notNull().default(false),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_org_units_tenant_id').on(table.tenant_id),
  unique('uq_app_org_units_tenant_id_id').on(table.tenant_id, table.id),
  index('idx_app_org_units_organization_id').on(table.organization_id),
  index('idx_app_org_units_cnes').on(table.cnes_code),
  index('idx_app_org_units_tax_id').on(table.tax_id),
  index('idx_app_org_units_cnpj').on(table.cnpj),
  index('idx_app_org_units_name').on(table.organization_id, table.name),
  foreignKey({ name: 'fk_app_org_units_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_org_units_organization', columns: [table.organization_id], foreignColumns: [appOrganizations.id] }).onDelete('restrict'),
]);

export const appRooms = pgTable('app_rooms', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  unit_id: varchar('unit_id', { length: 36 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  room_type: varchar('room_type', { length: 100 }),
  is_schedulable: boolean('is_schedulable').notNull(),
  equipment: text('equipment').array().notNull().default(sql`'{}'::text[]`),
  notes: text('notes'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_rooms_tenant_name').on(table.tenant_id, table.name, table.id),
  unique('uq_app_rooms_tenant_unit_id').on(table.tenant_id, table.unit_id, table.id),
  unique('uq_app_rooms_tenant_id').on(table.tenant_id, table.id),
  index('idx_app_rooms_tenant_unit').on(table.tenant_id, table.unit_id),
  foreignKey({ name: 'fk_app_rooms_unit', columns: [table.tenant_id, table.unit_id], foreignColumns: [appOrganizationUnits.tenant_id, appOrganizationUnits.id] }).onDelete('restrict'),
  check('app_rooms_name_check', sql`length(trim(${table.name})) > 0`),
]);

export const appPatients = pgTable('app_patients', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  full_name: varchar('full_name', { length: 255 }).notNull(),
  cpf: varchar('cpf', { length: 11 }),
  cns: varchar('cns', { length: 15 }),
  birth_date: date('birth_date'),
  gender: varchar('gender', { length: 20 }),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 20 }),
  address: text('address'),
  emergency_contact: varchar('emergency_contact', { length: 255 }),
  insurance_name: varchar('insurance_name', { length: 100 }),
  insurance_number: varchar('insurance_number', { length: 100 }),
  allergies_notes: text('allergies_notes'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_patients_tenant_id').on(table.tenant_id),
  unique('uq_app_patients_tenant_id_id').on(table.tenant_id, table.id),
  index('idx_app_patients_cpf').on(table.cpf),
  index('idx_app_patients_name').on(table.tenant_id, table.full_name),
  foreignKey({ name: 'fk_app_patients_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
]);

export const appPractitioners = pgTable('app_practitioners', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  user_id: varchar('user_id', { length: 36 }),
  full_name: varchar('full_name', { length: 255 }).notNull(),
  cpf: varchar('cpf', { length: 11 }),
  practitioner_type: varchar('practitioner_type', { length: 50 }).notNull(),
  job_title: varchar('job_title', { length: 100 }),
  council_type: varchar('council_type', { length: 20 }),
  council_number: varchar('council_number', { length: 20 }),
  council_uf: varchar('council_uf', { length: 2 }),
  primary_specialty: varchar('primary_specialty', { length: 150 }),
  phone: varchar('phone', { length: 20 }),
  email: varchar('email', { length: 255 }),
  is_clinical_staff: boolean('is_clinical_staff').notNull().default(false),
  birth_date: date('birth_date'),
  gender: varchar('gender', { length: 20 }),
  social_name: varchar('social_name', { length: 255 }),
  cns: varchar('cns', { length: 15 }),
  photo_url: varchar('photo_url', { length: 500 }),
  street: varchar('street', { length: 255 }),
  number: varchar('number', { length: 20 }),
  complement: varchar('complement', { length: 100 }),
  neighborhood: varchar('neighborhood', { length: 100 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 2 }),
  postal_code: varchar('postal_code', { length: 20 }),
  is_technical_lead: boolean('is_technical_lead').notNull().default(false),
  digital_signature_type: varchar('digital_signature_type', { length: 50 }).notNull().default('NONE'),
  calendar_color: varchar('calendar_color', { length: 20 }),
  notes: text('notes'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_practitioners_tenant_id').on(table.tenant_id),
  unique('uq_app_practitioners_tenant_id_id').on(table.tenant_id, table.id),
  index('idx_app_practitioners_user_id').on(table.user_id),
  index('idx_app_practitioners_cpf').on(table.cpf),
  index('idx_app_practitioners_type').on(table.practitioner_type),
  foreignKey({ name: 'fk_app_practitioners_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_practitioners_user', columns: [table.user_id], foreignColumns: [iamUsers.id] }).onDelete('set null'),
]);

export const appProcedures = pgTable('app_procedures', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  category: varchar('category', { length: 100 }),
  tuss_code: varchar('tuss_code', { length: 8 }),
  estimated_duration_minutes: integer('estimated_duration_minutes').notNull(),
  requires_room: boolean('requires_room').notNull().default(false),
  preparation_instructions: text('preparation_instructions'),
  return_after_days: integer('return_after_days'),
  minimum_interval_days: integer('minimum_interval_days'),
  calendar_color: varchar('calendar_color', { length: 7 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  unique('uq_app_procedures_tenant_id_id').on(table.tenant_id, table.id),
  index('idx_app_procedures_tenant_name').on(table.tenant_id, table.name, table.id),
  index('idx_app_procedures_tenant_tuss').on(table.tenant_id, table.tuss_code),
  foreignKey({ name: 'fk_app_procedures_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  check('app_procedures_name_check', sql`length(trim(${table.name})) > 0`),
  check('app_procedures_duration_check', sql`${table.estimated_duration_minutes} > 0`),
  check('app_procedures_return_check', sql`${table.return_after_days} >= 0`),
  check('app_procedures_interval_check', sql`${table.minimum_interval_days} >= 0`),
  check('app_procedures_tuss_check', sql`${table.tuss_code} ~ '^[0-9]{8}$'`),
  check('app_procedures_color_check', sql`${table.calendar_color} ~ '^#[0-9A-Fa-f]{6}$'`),
]);

export const appProcedurePractitioners = pgTable('app_procedure_practitioners', {
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  procedure_id: varchar('procedure_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
}, (table) => [
  unique('uq_app_procedure_practitioners').on(table.tenant_id, table.procedure_id, table.practitioner_id),
  index('idx_app_procedure_practitioners_practitioner').on(table.tenant_id, table.practitioner_id),
  foreignKey({ name: 'fk_app_procedure_practitioners_procedure', columns: [table.tenant_id, table.procedure_id], foreignColumns: [appProcedures.tenant_id, appProcedures.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_procedure_practitioners_practitioner', columns: [table.tenant_id, table.practitioner_id], foreignColumns: [appPractitioners.tenant_id, appPractitioners.id] }).onDelete('restrict'),
]);

export const appAvailabilities = pgTable('app_availabilities', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  unit_id: varchar('unit_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }),
  room_id: varchar('room_id', { length: 36 }),
  series_id: varchar('series_id', { length: 36 }).notNull(),
  replaces_id: varchar('replaces_id', { length: 36 }),
  day_of_week: integer('day_of_week').notNull(),
  start_time: varchar('start_time', { length: 5 }).notNull(),
  end_time: varchar('end_time', { length: 5 }).notNull(),
  slot_duration_minutes: integer('slot_duration_minutes').notNull(),
  timezone: varchar('timezone', { length: 100 }).notNull(),
  valid_from: date('valid_from').notNull(),
  valid_until: date('valid_until'),
  notes: text('notes'),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  unique('uq_app_availabilities_tenant_id').on(table.tenant_id, table.id),
  unique('uq_app_availabilities_replaces').on(table.tenant_id, table.replaces_id),
  foreignKey({ name: 'fk_app_availabilities_replaces', columns: [table.tenant_id, table.replaces_id], foreignColumns: [table.tenant_id, table.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_availabilities_series', columns: [table.tenant_id, table.series_id], foreignColumns: [table.tenant_id, table.id] }).onDelete('restrict'),
  index('idx_app_availabilities_series').on(table.tenant_id, table.series_id),
  index('idx_app_availabilities_resource').on(table.tenant_id, table.unit_id, table.practitioner_id, table.room_id),
  foreignKey({ name: 'fk_app_availabilities_unit', columns: [table.tenant_id, table.unit_id], foreignColumns: [appOrganizationUnits.tenant_id, appOrganizationUnits.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_availabilities_practitioner', columns: [table.tenant_id, table.practitioner_id], foreignColumns: [appPractitioners.tenant_id, appPractitioners.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_availabilities_room', columns: [table.tenant_id, table.unit_id, table.room_id], foreignColumns: [appRooms.tenant_id, appRooms.unit_id, appRooms.id] }).onDelete('restrict'),
  check('app_availabilities_resource_check', sql`(${table.practitioner_id} IS NULL) <> (${table.room_id} IS NULL)`),
  check('app_availabilities_day_check', sql`${table.day_of_week} BETWEEN 0 AND 6`),
  check('app_availabilities_time_check', sql`${table.start_time} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND ${table.end_time} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND ${table.start_time} < ${table.end_time}`),
  check('app_availabilities_slot_check', sql`${table.slot_duration_minutes} BETWEEN 1 AND 1439`),
  check('app_availabilities_validity_check', sql`${table.valid_until} IS NULL OR ${table.valid_until} > ${table.valid_from}`),
]);

export const appScheduleBlocks = pgTable('app_schedule_blocks', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  unit_id: varchar('unit_id', { length: 36 }),
  practitioner_id: varchar('practitioner_id', { length: 36 }),
  room_id: varchar('room_id', { length: 36 }),
  starts_at: timestamp('starts_at', { withTimezone: true }).notNull(),
  ends_at: timestamp('ends_at', { withTimezone: true }).notNull(),
  timezone: varchar('timezone', { length: 100 }).notNull(),
  reason: text('reason'),
  recurrence: jsonb('recurrence').$type<BlockRecurrence>(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_schedule_blocks_tenant_start').on(table.tenant_id, table.starts_at, table.id),
  index('idx_app_schedule_blocks_resource').on(table.tenant_id, table.practitioner_id, table.room_id),
  foreignKey({ name: 'fk_app_schedule_blocks_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_schedule_blocks_unit', columns: [table.tenant_id, table.unit_id], foreignColumns: [appOrganizationUnits.tenant_id, appOrganizationUnits.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_schedule_blocks_practitioner', columns: [table.tenant_id, table.practitioner_id], foreignColumns: [appPractitioners.tenant_id, appPractitioners.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_schedule_blocks_room', columns: [table.tenant_id, table.room_id], foreignColumns: [appRooms.tenant_id, appRooms.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_schedule_blocks_room_unit', columns: [table.tenant_id, table.unit_id, table.room_id], foreignColumns: [appRooms.tenant_id, appRooms.unit_id, appRooms.id] }).onDelete('restrict'),
  check('app_schedule_blocks_resource_check', sql`(${table.practitioner_id} IS NULL) <> (${table.room_id} IS NULL)`),
  check('app_schedule_blocks_period_check', sql`${table.ends_at} > ${table.starts_at}`),
  check('app_schedule_blocks_recurrence_check', sql`${table.recurrence} IS NULL OR (jsonb_typeof(${table.recurrence}) = 'object' AND ${table.recurrence} ? 'frequency' AND ${table.recurrence} ? 'interval' AND ${table.recurrence}->>'frequency' IN ('DAILY', 'WEEKLY') AND jsonb_typeof(${table.recurrence}->'interval') = 'number' AND (${table.recurrence}->>'interval')::numeric BETWEEN 1 AND 52 AND trunc((${table.recurrence}->>'interval')::numeric) = (${table.recurrence}->>'interval')::numeric)`),
]);

export const appAppointments = pgTable('app_appointments', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  patient_id: varchar('patient_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  procedure_id: varchar('procedure_id', { length: 36 }),
  unit_id: varchar('unit_id', { length: 36 }),
  room_id: varchar('room_id', { length: 36 }),
  is_overbook: boolean('is_overbook').notNull().default(false),
  payer_type: varchar('payer_type', { length: 20 }).$type<'PARTICULAR'>().notNull().default('PARTICULAR'),
  source_channel: varchar('source_channel', { length: 30 }).notNull().default('LEGACY'),
  appointment_date: timestamp('appointment_date', { withTimezone: true }).notNull(),
  duration_minutes: integer('duration_minutes').notNull(),
  status: varchar('status', { length: 20 }).notNull().default('SCHEDULED'),
  type: varchar('type', { length: 30 }).notNull(),
  notes: text('notes'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_appointments_tenant').on(table.tenant_id),
  index('idx_app_appointments_room').on(table.tenant_id, table.room_id, table.appointment_date),
  foreignKey({ name: 'fk_app_appointments_procedure', columns: [table.tenant_id, table.procedure_id], foreignColumns: [appProcedures.tenant_id, appProcedures.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_appointments_unit', columns: [table.tenant_id, table.unit_id], foreignColumns: [appOrganizationUnits.tenant_id, appOrganizationUnits.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_appointments_room_unit', columns: [table.tenant_id, table.unit_id, table.room_id], foreignColumns: [appRooms.tenant_id, appRooms.unit_id, appRooms.id] }).onDelete('restrict'),
  index('idx_app_appointments_patient').on(table.patient_id),
  index('idx_app_appointments_practitioner').on(table.practitioner_id),
  index('idx_app_appointments_date').on(table.appointment_date),
  foreignKey({ name: 'fk_app_appointments_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_appointments_patient', columns: [table.tenant_id, table.patient_id], foreignColumns: [appPatients.tenant_id, appPatients.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_appointments_practitioner', columns: [table.tenant_id, table.practitioner_id], foreignColumns: [appPractitioners.tenant_id, appPractitioners.id] }).onDelete('restrict'),
]);

export const appEncounters = pgTable('app_encounters', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  patient_id: varchar('patient_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  appointment_id: varchar('appointment_id', { length: 36 }),
  start_time: timestamp('start_time', { withTimezone: true }).notNull().defaultNow(),
  end_time: timestamp('end_time', { withTimezone: true }),
  status: varchar('status', { length: 20 }).notNull(),
  chief_complaint: text('chief_complaint'),
  diagnosis: text('diagnosis'),
  clinical_notes: text('clinical_notes'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_encounters_tenant').on(table.tenant_id),
  index('idx_app_encounters_patient').on(table.patient_id),
  index('idx_app_encounters_practitioner').on(table.practitioner_id),
  index('idx_app_encounters_start_time').on(table.start_time),
  foreignKey({ name: 'fk_app_encounters_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_encounters_patient', columns: [table.patient_id], foreignColumns: [appPatients.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_encounters_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_encounters_appointment', columns: [table.appointment_id], foreignColumns: [appAppointments.id] }).onDelete('set null'),
]);

export const appPrescriptions = pgTable('app_prescriptions', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  encounter_id: varchar('encounter_id', { length: 36 }).notNull(),
  patient_id: varchar('patient_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  medication_name: varchar('medication_name', { length: 255 }).notNull(),
  dosage: varchar('dosage', { length: 100 }).notNull(),
  instructions: text('instructions').notNull(),
  issued_at: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_prescriptions_tenant').on(table.tenant_id),
  index('idx_app_prescriptions_encounter').on(table.encounter_id),
  index('idx_app_prescriptions_patient').on(table.patient_id),
  foreignKey({ name: 'fk_app_prescriptions_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_prescriptions_encounter', columns: [table.encounter_id], foreignColumns: [appEncounters.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_prescriptions_patient', columns: [table.patient_id], foreignColumns: [appPatients.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_prescriptions_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('restrict'),
]);

export const appMedicalRecords = pgTable('app_medical_records', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  patient_id: varchar('patient_id', { length: 36 }).notNull(),
  encounter_id: varchar('encounter_id', { length: 36 }),
  record_type: varchar('record_type', { length: 30 }).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  content: text('content').notNull(),
  record_date: timestamp('record_date', { withTimezone: true }).notNull().defaultNow(),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_medical_records_tenant').on(table.tenant_id),
  index('idx_app_medical_records_patient').on(table.patient_id),
  foreignKey({ name: 'fk_app_medical_records_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_medical_records_patient', columns: [table.patient_id], foreignColumns: [appPatients.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_medical_records_encounter', columns: [table.encounter_id], foreignColumns: [appEncounters.id] }).onDelete('set null'),
]);


export const appSpecialties = pgTable('app_specialties', {
  id: varchar('id', { length: 36 }).primaryKey(),
  code: varchar('code', { length: 20 }).notNull(),
  name: varchar('name', { length: 100 }).notNull(),
  name_en: varchar('name_en', { length: 100 }),
  description: text('description'),
  cbo_code: varchar('cbo_code', { length: 10 }),
  fhir_code: varchar('fhir_code', { length: 50 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_specialties_code').on(table.code),
  index('idx_app_specialties_name').on(table.name),
]);

export const appPractitionerRegistrations = pgTable('app_practitioner_registrations', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  registration_type: varchar('registration_type', { length: 20 }).notNull(),
  registration_number: varchar('registration_number', { length: 50 }).notNull(),
  registration_state: varchar('registration_state', { length: 2 }),
  /** Marks the council that defines practitioner_type and the denormalized council_* columns. */
  is_primary: boolean('is_primary').notNull().default(false),
  issuing_body: varchar('issuing_body', { length: 100 }),
  issue_date: date('issue_date'),
  expiration_date: date('expiration_date'),
  status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
  verification_url: varchar('verification_url', { length: 500 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_pract_reg_tenant').on(table.tenant_id),
  index('idx_app_pract_reg_practitioner').on(table.practitioner_id),
  index('idx_app_pract_reg_number').on(table.registration_number, table.registration_type, table.registration_state),
  index('idx_app_pract_reg_primary').on(table.practitioner_id, table.is_primary),
  foreignKey({ name: 'fk_app_pract_reg_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_pract_reg_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('cascade'),
]);

export const appPractitionerSpecialties = pgTable('app_practitioner_specialties', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  specialty_id: varchar('specialty_id', { length: 36 }).notNull(),
  is_primary: boolean('is_primary').notNull().default(false),
  qualification_date: date('qualification_date'),
  rqe_number: varchar('rqe_number', { length: 50 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_pract_spec_tenant').on(table.tenant_id),
  index('idx_app_pract_spec_practitioner').on(table.practitioner_id),
  index('idx_app_pract_spec_specialty').on(table.specialty_id),
  index('idx_app_pract_spec_primary').on(table.practitioner_id, table.is_primary),
  foreignKey({ name: 'fk_app_pract_spec_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_pract_spec_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_pract_spec_specialty', columns: [table.specialty_id], foreignColumns: [appSpecialties.id] }).onDelete('restrict'),
]);

export const appPractitionerQualifications = pgTable('app_practitioner_qualifications', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  qualification_type: varchar('qualification_type', { length: 50 }).notNull(),
  issuing_institution: varchar('issuing_institution', { length: 255 }).notNull(),
  degree_name: varchar('degree_name', { length: 255 }).notNull(),
  year_issued: integer('year_issued').notNull(),
  country_code: varchar('country_code', { length: 2 }),
  valid_until: date('valid_until'),
  document_url: varchar('document_url', { length: 500 }),
  verified: boolean('verified').notNull().default(false),
  verified_by: varchar('verified_by', { length: 36 }),
  verified_at: timestamp('verified_at', { withTimezone: true }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_pract_qual_tenant').on(table.tenant_id),
  index('idx_app_pract_qual_practitioner').on(table.practitioner_id),
  foreignKey({ name: 'fk_app_pract_qual_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_pract_qual_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_pract_qual_verified_by', columns: [table.verified_by], foreignColumns: [iamUsers.id] }).onDelete('set null'),
]);

export const appPractitionerAvailability = pgTable('app_practitioner_availability', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  practitioner_id: varchar('practitioner_id', { length: 36 }).notNull(),
  organization_unit_id: varchar('organization_unit_id', { length: 36 }),
  /** Sunday is 0 — same convention as app_availabilities.day_of_week. */
  day_of_week: integer('day_of_week').notNull(),
  start_time: varchar('start_time', { length: 10 }).notNull(),
  end_time: varchar('end_time', { length: 10 }).notNull(),
  lunch_start: varchar('lunch_start', { length: 10 }),
  lunch_end: varchar('lunch_end', { length: 10 }),
  slot_duration_minutes: integer('slot_duration_minutes').notNull().default(30),
  room_id: varchar('room_id', { length: 36 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_pract_avail_tenant').on(table.tenant_id),
  index('idx_app_pract_avail_practitioner').on(table.practitioner_id),
  index('idx_app_pract_avail_unit').on(table.organization_unit_id),
  check('app_practitioner_availability_day_check', sql`${table.day_of_week} BETWEEN 0 AND 6`),
  foreignKey({ name: 'fk_app_pract_avail_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_pract_avail_practitioner', columns: [table.practitioner_id], foreignColumns: [appPractitioners.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_pract_avail_unit', columns: [table.organization_unit_id], foreignColumns: [appOrganizationUnits.id] }).onDelete('set null'),
]);

export const appStaff = pgTable('app_staff', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  user_id: varchar('user_id', { length: 36 }).notNull(),
  full_name: varchar('full_name', { length: 255 }).notNull(),
  cpf: varchar('cpf', { length: 11 }).notNull(),
  rg: varchar('rg', { length: 20 }),
  birth_date: date('birth_date').notNull(),
  gender: varchar('gender', { length: 20 }),
  staff_type: varchar('staff_type', { length: 50 }).notNull(),
  department: varchar('department', { length: 100 }),
  job_position: varchar('job_position', { length: 100 }),
  contract_type: varchar('contract_type', { length: 50 }),
  hire_date: date('hire_date').notNull(),
  termination_date: date('termination_date'),
  phone: varchar('phone', { length: 20 }),
  email: varchar('email', { length: 255 }).notNull(),
  emergency_contact_name: varchar('emergency_contact_name', { length: 255 }),
  emergency_contact_phone: varchar('emergency_contact_phone', { length: 20 }),
  street: varchar('street', { length: 255 }),
  number: varchar('number', { length: 20 }),
  complement: varchar('complement', { length: 100 }),
  neighborhood: varchar('neighborhood', { length: 100 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 2 }),
  postal_code: varchar('postal_code', { length: 20 }),
  photo_url: varchar('photo_url', { length: 500 }),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
}, (table) => [
  index('idx_app_staff_tenant_id').on(table.tenant_id),
  index('idx_app_staff_user_id').on(table.user_id),
  index('idx_app_staff_cpf').on(table.cpf),
  index('idx_app_staff_type').on(table.staff_type),
  foreignKey({ name: 'fk_app_staff_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_staff_user', columns: [table.user_id], foreignColumns: [iamUsers.id] }).onDelete('restrict'),
]);

export const appStaffQualifications = pgTable('app_staff_qualifications', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  staff_id: varchar('staff_id', { length: 36 }).notNull(),
  qualification_type: varchar('qualification_type', { length: 50 }).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  issuing_institution: varchar('issuing_institution', { length: 255 }),
  year_issued: integer('year_issued'),
  valid_until: date('valid_until'),
  is_active: boolean('is_active').notNull().default(true),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_app_staff_qual_tenant').on(table.tenant_id),
  index('idx_app_staff_qual_staff').on(table.staff_id),
  foreignKey({ name: 'fk_app_staff_qual_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_staff_qual_staff', columns: [table.staff_id], foreignColumns: [appStaff.id] }).onDelete('cascade'),
]);

export const appStaffUnits = pgTable('app_staff_units', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tenant_id: varchar('tenant_id', { length: 36 }).notNull(),
  staff_id: varchar('staff_id', { length: 36 }).notNull(),
  organization_unit_id: varchar('organization_unit_id', { length: 36 }).notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique('uq_app_staff_units_staff_unit').on(table.staff_id, table.organization_unit_id),
  index('idx_app_staff_units_tenant').on(table.tenant_id),
  index('idx_app_staff_units_staff').on(table.staff_id),
  index('idx_app_staff_units_unit').on(table.organization_unit_id),
  foreignKey({ name: 'fk_app_staff_units_tenant', columns: [table.tenant_id], foreignColumns: [sysTenants.id] }).onDelete('restrict'),
  foreignKey({ name: 'fk_app_staff_units_staff', columns: [table.staff_id], foreignColumns: [appStaff.id] }).onDelete('cascade'),
  foreignKey({ name: 'fk_app_staff_units_unit', columns: [table.organization_unit_id], foreignColumns: [appOrganizationUnits.id] }).onDelete('restrict'),
]);
